/**
 * Minimal spirit seed for world state. The content fork owns the richer
 * prose (channel voices, bargains); the DO initialises `state.spirits` from
 * this so regard, wants and anchors exist from the first tick.
 */
import type { CellRef, Spirit, SpiritId } from "../types.js";

type Seed = Omit<Spirit, "regard" | "named" | "awake" | "reserve" | "anchor"> & { anchor: CellRef; awake?: boolean };

const seeds: Seed[] = [
  { id: "hearth", title: "the Hearth", trueName: "Hamanith", meaning: "heat within", anchor: { region: "manor", x: 12, y: 8 }, wants: "the fire kept, and the household home", wantList: [{ id: "hearth-lit", text: "the fire lit", met: false }, { id: "household-home", text: "the household together at the bell hour", met: false }, { id: "garden-fed", text: "the kitchen garden feeding the house", met: false }], temper: "warm; likes you first; notices absence", hour: "dawn", colour: "#d9772b", ornament: "❧", knows: ["estan", "household names", "the familiar's habits"], awake: true },
  { id: "river", title: "the River", trueName: "Velharan", meaning: "the flow that holds", anchor: { region: "upper-reach", x: 24, y: 6 }, wants: "the wheel turning; the sluices clear", wantList: [{ id: "wheel-turns", text: "the wheel turning", met: false }, { id: "sluices-clear", text: "the sluices clear of silt", met: false }, { id: "carp", text: "carp in the marsh", met: false }], temper: "patient, literal; never lies; never volunteers", hour: "noon", colour: "#3f7f9f", ornament: "≋", knows: ["vel", "sen", "kir", "silt", "the mill's name", "the grate's weakness"] },
  { id: "library", title: "the Library", trueName: "Thesaurin", meaning: "the kept quenching", anchor: { region: "library", x: 16, y: 12 }, wants: "the shelves dried; the books in order", wantList: [{ id: "shelves-dry", text: "the shelves dried", met: false }, { id: "notebooks-restored", text: "the notebooks restored", met: false }, { id: "order", text: "order kept", met: false }], temper: "pedantic; generous at a price; prices in sap and order", hour: "evening", colour: "#6d5a8e", ornament: "¶", knows: ["the master's index", "binding words", "old form", "rune-craft"] },
  { id: "foundry", title: "the Foundry", trueName: "Hahamadath", meaning: "great heat that breaks", anchor: { region: "foundry", x: 10, y: 8 }, wants: "heat, always more; to be used", wantList: [{ id: "lit", text: "the furnace lit", met: false }, { id: "used", text: "to be used for glass", met: false }], temper: "careless, exuberant; must be warded, and knows it", hour: "night", colour: "#c8412b", ornament: "✶", knows: ["glass", "silver", "asha", "dath"] },
  { id: "mill", title: "the Mill", trueName: "Doranvel", meaning: "stone and flow", anchor: { region: "mill", x: 10, y: 8 }, wants: "to turn", wantList: [{ id: "turn", text: "to turn", met: false }], temper: "steady, dull, honest", hour: "noon", colour: "#8a7a5a", ornament: "⚙", knows: ["power", "gearing", "bral", "the Foundry's tells"] },
  { id: "bell", title: "the Bell", trueName: "Tantanoes", meaning: "the many dusks", anchor: { region: "bell-tower", x: 4, y: 4 }, wants: "true time; the festivals rung", wantList: [{ id: "mended", text: "the crack mended", met: false }, { id: "rung", text: "a festival rung properly", met: false }], temper: "anxious; once repaired, exact and proud", hour: "hourly, briefly", colour: "#b8a24a", ornament: "♩", knows: ["the sky's words", "storms", "lunae"] },
  { id: "glass", title: "the Glass", trueName: "Lumevitre", meaning: "light held", anchor: { region: "glassworks", x: 8, y: 6 }, wants: "its roof; light; lenses again; a charm it approves of", wantList: [{ id: "roof", text: "the roof raised", met: false }, { id: "charm", text: "a charm it approves of", met: false }, { id: "lenses", text: "lenses again", met: false }], temper: "vain, exacting, cold; keeps charms it liked", hour: "dusk", colour: "#9ad0d8", ornament: "◈", knows: ["foci", "vitre", "the lenses"] },
  { id: "orchard", title: "the Orchard", trueName: "Saelolath", meaning: "all growth beyond", anchor: { region: "orchard", x: 20, y: 16 }, wants: "the sluice mended; seasons kept", wantList: [{ id: "sluice", text: "Ilvane's sluice mended", met: false }, { id: "seasons", text: "the seasons kept", met: false }, { id: "sap-given", text: "sap given, not taken", met: false }], temper: "slow, generous, wounded", hour: "afternoon", colour: "#5e8f3e", ornament: "❀", knows: ["species", "sapa", "Ilvane's ward"] },
  { id: "deep", title: "the Deep", trueName: "Morithedor", meaning: "cold rot in stone", anchor: { region: "mine-deep", x: 16, y: 12 }, wants: "to be left alone", wantList: [{ id: "alone", text: "to be left alone", met: true }, { id: "understood", text: "to be understood", met: false }], temper: "reluctant; frightened; not evil", hour: "never, unless spoken to", colour: "#3b3b4f", ornament: "▾", knows: ["Corwen's charter", "oss", "the seam's way"] },
  { id: "boneyard", title: "the Boneyard", trueName: "Ossnem", meaning: "bone named", anchor: { region: "boneyard", x: 8, y: 8 }, wants: "its dead named; Corwen's golems released", wantList: [{ id: "named", text: "its dead named", met: false }, { id: "released", text: "Corwen's golems released", met: false }], temper: "grave, courteous; gives if asked rightly", hour: "midnight", colour: "#a99e8a", ornament: "☗", knows: ["names of the dead", "nem", "forbidden words"] },
  { id: "ridge", title: "the Ridge", trueName: "Norael", meaning: "north-all", anchor: { region: "ridge", x: 56, y: 4 }, wants: "the cairns raised; the third line straight", wantList: [{ id: "cairns", text: "the cairns raised", met: false }, { id: "third-line", text: "the third line straight", met: false }], temper: "vast, slow; speaks in weather", hour: "before storms", colour: "#7f8fa6", ornament: "△", knows: ["ley", "aethe", "weather before it comes"] },
  { id: "moor", title: "the Moor", trueName: "many", meaning: "the deep tongue said badly", anchor: { region: "near-moor", x: 32, y: 4 }, wants: "in", wantList: [{ id: "in", text: "in", met: false }], temper: "adversarial; adaptive; bargains at cost", hour: "autumn nights", colour: "#6a3d7a", ornament: "⁂", knows: ["rot", "wind", "the wall's weakness", "stolen names"], awake: true },
  { id: "echo", title: "the Master's echo", trueName: "Ysolde", meaning: "Ysolde Marrow, the last master", anchor: { region: "observatory", x: 12, y: 12 }, wants: "to finish", wantList: [{ id: "finish", text: "to finish", met: false }], temper: "brief, unbidden, kind", hour: "when scrying her spells", colour: "#c9b8d8", ornament: "✎", knows: ["fragments"] },
];

export const SPIRIT_SEED: Record<SpiritId, Spirit> = Object.fromEntries(
  seeds.map((s) => [s.id, { ...s, regard: {}, named: false, awake: s.awake ?? false, reserve: 20 } satisfies Spirit]),
) as Record<SpiritId, Spirit>;
