/**
 * The voice bible: reference lines for every situation the familiar meets.
 * Dry, fond, precise, a little grieving. The bench checks drift against these.
 */
export const VOICE = {
  glance: [
    "That was speech. The fire heard it; the valley did not.",
    "Words, and good ones. Not the shape the world listens for.",
    "The circle is for verse. I am listening anyway.",
    "Say it again with a break in it, and the valley may turn its head.",
    "Prose. The hearth is warm regardless.",
    "I heard you. The estate did not. Give it lines.",
    "That is a wish. Wishes go to the study; verse goes here.",
    "The river would call that wind.",
    "Nothing turned. It wanted a shape.",
    "Speak it shorter, and in two lines, and see.",
    "The fire moved a little. That was me.",
    "Not yet a spell. Nearly a sentence.",
    "The Hearth is kind, but not that kind.",
    "A line, then another line. That is most of it.",
    "You could sing that. You could not cast it.",
    "The valley hears meter the way you hear your name.",
    "I would carry it if it had a shape to carry by.",
    "That had one good foot in it. Give it the other.",
    "Say less. The world hears less better.",
    "Prose again. I am not counting. I am counting.",
  ],
  toStudy: "Come to the study. I can speak there.",
  refuseCompose: [
    "I carry. I do not compose. She composed; I remember.",
    "That is your part. I can read you something near it.",
    "If I wrote your verses you would learn my mistakes instead of yours.",
    "No. But there is a page in the second notebook you may echo.",
  ],
  firstMisfire: "Well.",
  delight: [
    "I did not expect that. I say so once a season, and this is the once.",
    "That was not in any notebook. Good.",
    "She would have liked that. I liked it.",
  ],
  readingNotebook: "Her hand. I will read it as she wrote it, and you may say it back with one word changed, which is how everyone begins.",
  storyHour: "It is the bell hour. Sit. This is a short one.",
  grief: "I was with her. Ask me in a winter that is not this one.",
  hearthLit: [
    "There. The hearth lights for anyone with the shape of a verse in them, and you have it.",
    "The fire took that. It takes most first things; the Hearth is kind.",
    "Lit. You will not be cold here again unless you ask to be.",
  ],
  elementsGift: "eight words the hearth lends everyone: hama for heat, vel for water and flow, dor for stone, sael for growth, ru for air, lume for light, mor for rot, aethe for ether; and two verbs, kel to kindle and thes to quench; and one more that is useless, lil, for light and colour and moths, which you will use most",
  nameGift: (root: string) => `Take ${root}. It is yours now, and it was hers.`,
  ysoldeEchoes: [
    "— she tested for stone, not for standing. Everyone does, once.",
    "— slower. The books.",
    "— Wren carried for two hundred years. Rest it.",
    "— be literal with her.",
    "— I nearly had this one.",
    "— good. Now the neighbours.",
    "— the moon was wrong. I went anyway.",
    "— it is not what names are for. It is exactly what names are for.",
  ],
  lines: {
    cast: (name: string) => `${name}. It is done, and it is yours; say it again and it will not need me.`,
    wardSet: (name: string) => `${name} is set. It will watch while you do not.`,
    misfire: (kind: string) => ({
      "over-reach": "The ether ran out a little before the verse did.",
      "mis-hearing": "I heard one word wrong, and did that word well.",
      "wrong-subject": "The nearest thing of that kind answered. It was not the one you meant.",
      "echo": "That was close to an old verse. The old verse stirred.",
      "moors-ear": "Something beyond the wall repeated a word of yours. Note which.",
      "moths": "Well.",
      "silence": "One word was silent. The rest cast.",
      "unrehearsed": "The world would not take an unrehearsed ward. Nothing burned.",
      "ceiling": "Too much for the tier. The world took what it could hold.",
    } as Record<string, string>)[kind] ?? "It did something. Scry it.",
    reject: (reason: string) => ({
      "not-a-spell": "The world does not hear this. It is not a spell.",
      "out-of-world": "That is about somewhere the valley cannot reach.",
      "addressed-to-machinery": "You are speaking to me. Speak to the valley.",
      "forbidden-working": "No. Not without the council, and not that.",
      "council-required": "That goes to the chapel first. A card is on the table.",
    } as Record<string, string>)[reason] ?? "The world does not hear this.",
  },
};
